name: Checks

on: [push]

env:
  POETRY_VERSION: 1.5.1

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - name: Install Poetry
        uses: snok/install-poetry@v2
        with:
          version: $POETRY_VERSION
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Test
        run: poetry run pytest
      - name: Lint
        run: flake8 --max-line-length 120  --exclude=*/migrations/*